apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: container-registry-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: container-registry-example
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization