#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Annaliskirwa
          password: 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
      - name: Maven
        run: |
          mvn -B package --file pom.xm
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/annaliskirwa/hello-docker-gcr-demo:latest
          docker push ghcr.io/annaliskirwa/hello-docker-gcr-demo:latest
      - name: Connect with openshift
        run: |
          oc login --token=sha256~LArk6ZTXUsTEqBH0VB8FRltrpBUKgnqZ2ZKE5pztJ-M --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      - name: Select openshift project
        run: |
          oc project marynjenga910-dev
      - name: Deploy deployment files
        run: |
          oc apply -f /ocp -n marynjenga910-dev
