#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Annaliskirwa
          password: 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
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/annaliskirwa/hello-docker-gcr-demo:latest
          docker push ghcr.io/annaliskirwa/hello-docker-gcr-demo:latest