#publish your docker image to github container registry

name: publish

on: [ push ]

jobs:

  publish-hello-docker-image:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry

        uses: docker/login-action@v1

        with:

          registry: ghcr.io

          username: Annaliskirwa

          password: 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

      - name: Build the hello-docker Docker image

        run: |

          docker build . --tag ghcr.io/Annaliskirwa/container-registry:latest

          docker run ghcr.io/Annaliskirwa/container-registry:latest

          docker push ghcr.io/Annaliskirwa/container-registry:latest